### ISSUE TITLE
Cannot use with Kotlin 1.2.x

### ISSUE THREAD

**Issue by adrian5632** [pfn/kotlin-plugin#23]
Hi there. It seems that I am unable to compile projects when using Kotlin 1.2. Here's the error:

<pre>`[info] Compiling 119 Kotlin sources
java.lang.NoSuchFieldException: freeArgs
	at java.lang.Class.getField(Class.java:1703)
	at kotlin.KotlinStub$$anon$1.updateDynamic(KotlinCompile.scala:173)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at kotlin.KotlinCompile$.compile(KotlinCompile.scala:54)
	at kotlin.KotlinPlugin$$anonfun$5.apply(KotlinPlugin.scala:65)
	at kotlin.KotlinPlugin$$anonfun$5.apply(KotlinPlugin.scala:64)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (compile:kotlinCompile) java.lang.NoSuchFieldException: freeArgs`</pre>

Any idea how to fix it? I need to deploy one of my projects soon and would like to do this using 1.2.x due to some features not available prior to that version.

**Comment by aki-ks** [comment]
Kotlin's compiler-arguments class now uses getters and setters instead of fields.
Therefore [`compilerArgs`](https://github.com/pfn/kotlin-plugin/blob/931fa366adb6196c83e1e509f3098d0682184a34/src/main/scala/KotlinCompile.scala#L161-L174) in KotlinCompile.scala must be modified:
``` scala
def compilerArgs = {
  import language.dynamics
  new Dynamic {
    def withFirstUpper(string: String): String = string.head.toUpper + string.tail
    def getterName(field: String) = s"get${withFirstUpper(field)}"
    def setterName(field: String) = s"set${withFirstUpper(field)}"

    def selectDynamic[A](field: String): A = {
      val methodName = getterName(field)
      val getterOpt = compilerArgsClass.getMethods.find(_.getName == methodName)
      getterOpt match {
        case Some(getter) => getter.invoke(instance).asInstanceOf[A]
        case None => compilerArgsClass.getField(field).get(instance).asInstanceOf[A]
      }
    }

    def updateDynamic(field: String)(value: Any): Unit = {
      val methodName = setterName(field)
      val setterOpt = compilerArgsClass.getMethods.find(_.getName == methodName)
      setterOpt match {
        case Some(setter) => setter.invoke(instance, value.asInstanceOf[Object])
        case None => compilerArgsClass.getField(field).set(instance, value)
      }
    }

    val instance = compilerArgsClass.newInstance().asInstanceOf[AnyRef]
  }
}
```
