### ISSUE TITLE
Compatibility issue with Kotlin 1.7.0

### ISSUE THREAD

**Issue by slandelle** [pfn/kotlin-plugin#44]
Hi,

Sadly, the siganture has changed:

```
[error] java.lang.NoSuchMethodException: org.jetbrains.kotlin.cli.common.arguments.ParseCommandLineArgumentsKt.parseCommandLineArguments(java.util.List, org.jetbrains.kotlin.cli.common.arguments.CommonToolArguments)
[error] 	at java.lang.Class.getMethod(Class.java:1786)
[error] 	at kotlin.KotlinStub.parse(KotlinCompile.scala:156)
[error] 	at kotlin.KotlinCompile$.compile(KotlinCompile.scala:37)
[error] 	at kotlin.KotlinPlugin$.$anonfun$kotlinCompileSettings$4(KotlinPlugin.scala:82)
[error] 	at kotlin.KotlinPlugin$.$anonfun$kotlinCompileSettings$4$adapted(KotlinPlugin.scala:78)
```

**Comment by jeffboutotte** [comment]
If you still need this and haven't already done the same, we've been using the code from #45 internally for some time now with just an internal fork/internally published artifact. Not sure on turnaround time for review/publishing from this official repo but I just noticed this issue and figured I'd kick back a cherry-picked fix for the broader community.

**Comment by slandelle** [comment]
@jeffboutotte Thanks a bunch, that's really great of you!

Yes, we need this, and published in a public repo so [it can be used by GitHub Action CI on our public repo](https://github.com/gatling/gatling/blob/main/project/plugins.sbt#L8).

@pfn do you think you'll be able to merge and release? Or should we look for another solution?

**Comment by He-Pin** [comment]
It would be great if Kotlin 1.7.10 is supported with a new release.

**Comment by jxnu-liguobin** [comment]
@He-Pin https://github.com/bitlap/kotlin-plugin, I will maintain the fork to develop  [intellij-sbt-dependency-analyzer](https://github.com/bitlap/intellij-sbt-dependency-analyzer), now supports kotlin 1.9.0.
